name: Build App
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Username'
        required: true
        default: 'Luix'
      password:
        description: 'Password'
        required: true        

jobs:
  build_artifact:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "Testado!"